### ISSUE TITLE
 Interactivity Settings disableMobile Not Working for Mobile Devices

### ISSUE THREAD

**Issue by isvoria** [GeorgeHastings/embed-unicornstudio#1]
(Love your product) However, seems to be a problem with:

UnicornStudio.addScene({
      // These params are required;
      elementId: 'id',
      projectId: 'pid', 

      // These params are optional;
      fps: 60,
      scale: 1,
      dpi: 1,
      interactivity: {
        mouse: {
          disableMobile: true,
          momentum: 1.1
        },
        scroll: {
          disableMobile: true,
          momentum: 1.1
        }
      }
    }).then(() => {
      // Scene is ready
    }).catch((err) => {
      console.error(err);
    });

As it still are interactions on mobile even when set to false. Could not find out why this happens or how to fix this.

**Comment by GeorgeHastings** [comment]
My apologies for the delay! Will set up notifications for these. 

This issue is fixed in v1.1.0, disable mobile should work as expected with `data-us-disableMobile="true"` inline or as a param like you have it in your example.
