### ISSUE TITLE
Incorrect `aria-role`

### ISSUE THREAD

**Issue by elliottmangham** [GeorgeHastings/embed-unicornstudio#5]
The canvas is currently set to `aria-role="image"`, which is not valid. Please modify it to `img` according to the ARIA specification: [https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/img_role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/img_role).

Thank you!

**Comment by GeorgeHastings** [comment]
Thank you, fixed in 1.3.2!
